unitsDict = {'m':1.0,
            'cm':1.0E-2,
            'mm':1.0E-3,
            'm-1':1.0,
            'cm-1':1.0E2,
            'mm-1':1.0E3,
            'm2':1.0,
            'cm2':1.E-4,
            'mm2':1.E-6,
            'm-2':1.0,
            'cm-2':1.E4,
            'mm-2':1.E6,
            'm3':1.0,
            'cm3':1E-6,
            'mm3':1E-9,
            'm-3':1.0,
            'cm-3':1.0E6,
            'mm-3':1.0E9,
            'Pa':1.0,
            'Pa-1':1.0,
            'mmHg':133.32,
            'mmHg-1':1.0/133.32,
            'ml': 1E-6,
            'ml-1':1E6,
            'N':  1.0,
            'N-1':1.0,
            's':  1.0,
            's2': 1.0,
            's-2':1.0,
            's-1':1.0,
            'min': 60.0,
            'min-1': 1.0/60.0,
            'min2': 3600.0,
            'min-2': 1.0/3600.0,
            'e6':1.E6,
            'e5':1.E5,
            'e4':1.E4,
            'e3':1.0E3, 
            'e2':1.0E2,
            'e-6':1.E-6,
            'e-5':1.E-5,
            'e-4':1.E-4,
            'e-3':1.0E-3, 
            'e-2':1.0E-2,
            '' : 1.0,
            ' ':1.0,
            'kg': 1.0,
            'g': 1.E-3,
            'mg': 1.E-6
            }

bcTags = {'Rt':['Rt'],
          'R':['Rc'],
          'WK2':['Rc','C'],
          'WK3':['Rc','C','R1','RT'],
          'QPhy':['amp','Npulse','freq','Tpulse','Tspace'],
          'Qa':['amp','Npulse','freq'],
          'Q2a':['amp','Npulse','freq','Tpulse'],
          'Qm':['mean','Tmean','Traise'],
          'Q2m':['amp','Tmean','Traise'],
          'Ue':['amp','C','Tpulse'],
          'Pa':['amp','Npulse','freq'],
          'P2a':['amp','Npulse','freq','Tpulse'],
          'Pm':['mean','Tmean','Traise'],
          'P2m':['amp','Tmean','Traise'],
          'Fou':['amp','Tmean','Traise','scale','Npulse','Tpulse'],
          'PhyQ':[''],
          'Lnet':['Z','C'],
          '_Rt':['Rt'],
          '_R':['Rc'],
          '_WK2':['Rc','C'],
          '_WK3':['Rc','C','R1','RT'],
          '_QPhy':['amp','Npulse','freq','Tpulse','Tspace'],
          '_Qa':['amp','Npulse','freq'],
          '_Q2a':['amp','Npulse','freq','Tpulse'],
          '_Qm':['mean','Tmean','Traise'],
          '_Q2m':['amp','Tmean','Traise'],
          '_Ue':['amp','C','Tpulse'],
          '_Pa':['amp','Npulse','freq'],
          '_P2a':['amp','Npulse','freq','Tpulse'],
          '_Pm':['mean','Tmean','Traise'],
          '_P2m':['amp','Tmean','Traise'],
          '_Fou':['amp','Tmean','Traise','scale','Npulse','Tpulse'],
          '_PhyQ':[''],
          '_Lnet':['Z','C'],
          'None':['']}  

bcTagsUnits = {'Rt': '',
               'Rc':'Pa s m-3',
               'C':'m3 Pa-1',
               'R1':'Pa s m-3',
               'RT':'Pa s m-3',
               'Z':'Pa s m-3',
               'amp':'Pa',
               'Tmean': 's',
               'Traise': 's',
               'Tpulse': 's',
               'Tspace': 's',
               'Npulse': '',
               'scale': '',
               'freq': 's-1'}

bcTagsClassReferences = { 'Rt'  :'Terminal',
                          'R'   :'Resistance',
                          'WK2' :'Windkessel2',
                          'WK3' :'Windkessel3',
                          'QPhy':'PhysiologicalFunction',
                          'Qa'  :'Sinus',
                          'Q2a' :'Sinus2',
                          'Qm'  :'Mean',
                          'Q2m' :'Mean',
                          'Ue'  :'expVelocity',
                          'Pa'  :'Sinus',
                          'P2a' :'Sinus2',
                          'Pm'  :'Mean',
                          'P2m' :'Mean',
                          'Fou' :'Fourier',
                          'PhyQ':'Physiological',
                          'Lnet':'L_network',
                          '_Rt'  :'Terminal',
                          '_R'   :'Resistance',
                          '_WK2' :'Windkessel2',
                          '_WK3' :'Windkessel3',
                          '_QPhy':'PhysiologicalFunction',
                          '_Qa'  :'Sinus',
                          '_Q2a' :'Sinus2',
                          '_Qm'  :'Mean',
                          '_Q2m' :'Mean',
                          '_Ue'  :'expVelocity',
                          '_Pa'  :'Sinus',
                          '_P2a' :'Sinus2',
                          '_Pm'  :'Mean',
                          '_P2m' :'Mean',
                          '_Fou' :'Fourier',
                          '_PhyQ':'Physiological',
                          '_Lnet':'L_network'} 
import numpy as np
bcDuMatrix = {'Qa'  :np.array([0,1]),
              'Q2a' :np.array([0,1]),
              'Qm'  :np.array([0,1]),
              'Q2m' :np.array([0,1]),
              'Pa'  :np.array([1,0]),
              'P2a' :np.array([1,0]),
              'Pm'  :np.array([1,0]),
              'P2m' :np.array([1,0]),
              '_Qa'  :np.array([0,1]),
              '_Q2a' :np.array([0,1]),
              '_Qm'  :np.array([0,1]),
              '_Q2m' :np.array([0,1]),
              '_Pa'  :np.array([1,0]),
              '_P2a' :np.array([1,0]),
              '_Pm'  :np.array([1,0]),
              '_P2m' :np.array([1,0])}

